### ISSUE TITLE
Cannot Resolve Symbol 'BreakpointProvider'

### ISSUE THREAD

**Issue by clarkbrent** [flexdinesh/react-socks#12]
I'm currently testing out your library. I love the idea! However, when I try to import BreakpointProvider in my project, I receive an error, `Cannot Resolve Symbol 'BreakpointProvider'`. Outside of that, the breakpoints don't seem to be triggered. The root component only seems to load the component in the first Breakpoint (TabNav) regardless of whatever resolution I use.

```javascript
import React from 'react';
import Breakpoint, { BreakpointProvider } from 'react-socks';

const TabNav = React.lazy(() => import('./TabNav'));
const ListNav = React.lazy(() => import('./ListNav'));

const Example = () => {
  return (
    <BreakpointProvider>
      <div className="example">
          <Breakpoint small down>
            <TabNav />
          </Breakpoint>
          <Breakpoint medium up>
            <ListNav />
          </Breakpoint>
      </div>
    </BreakpointProvider>
  );
};

export default Example;

```
I've also tried replacing both the TabNav and ListNav components with simple text in each breakpoint. The text in both breakpoints is displayed when the DOM is rendered regardless of the resolution.

React-Socks: 1.0.1
React: 16.8.1

**Comment by flexdinesh** [comment]
@clarkbrent I just double checked in a local project and in codesandbox. It seems to work fine for me without any hiccups. Perhaps, could you add additional details on when this is happening?

Here's a codesandbox example for you to play around with - [React Socks Demo](https://codesandbox.io/s/ym7qm7jzr1)

**Comment by clarkbrent** [comment]
@flexdinesh I just reset my entire node_modules folder, and it seems to be working now. The only other thing I can think that it may have been was a rogue CSS selector that was getting priority, and messing something up? Not sure, but it seems to be working now.

Thanks again!
