### ISSUE TITLE
React should be a peer dependency

### ISSUE THREAD

**Issue by flexdinesh** [flexdinesh/react-socks#2]
React is now a dependency and built along with the package and makes the lib heavy. React should be a peer dependency.

Take a look at [styled-components](https://github.com/styled-components/styled-components/blob/master/package.json) for base version ideas.

Originally brought up in another PR by @sadarshannaiynar

**Comment by sadarshannaiynar** [comment]
@flexdinesh This alone doesn't solve the problem when you build it again takes react and other libraries.

**Comment by flexdinesh** [comment]
@sadarshannaiynar what's the ideal approach for this?

**Comment by sadarshannaiynar** [comment]
@flexdinesh Hey, I have created a PR regarding this in the boilerplate package. Please take a look into that. I didn't want to modify here as this is published, once you are okay with the approach there we can proceed in implementing the same here.

**Comment by flexdinesh** [comment]
@sadarshannaiynar Thanks for pointing this out again. I've now followed the same approach we used in the boilerplate to prevent bundling peer dependencies.

cb6f2cb691f76761511bc3bdfeb32ae3789a6ac4 address this issue. Closing for now.
