### ISSUE TITLE
Consider throttling the window resize event

### ISSUE THREAD

**Issue by wuz** [flexdinesh/react-socks#3]
React already throttles calls to setState, which is the only thing in the resize function currently - however it might be more clear/worthwhile in the future to throttle [this function](https://github.com/flexdinesh/react-socks/blob/master/src/Breakpoint/Breakpoint.js#L18): 

```js
  componentDidMount() {
    window.addEventListener('resize', () => {
      this.setState({
        width: BreakpointUtil.currentWidth,
        currentBreakpoint: BreakpointUtil.currentBreakpointName
      });
    });
}
```

Cool library! Definitely look forward to trying it out on a project!

**Comment by flexdinesh** [comment]
@wuz We definitely need this. Feel free to create a PR if you this mind mapped already.
