### ISSUE TITLE
Server-side rendering issue

### ISSUE THREAD

**Issue by timoisalive** [flexdinesh/react-socks#6]
I'd like to try out the library, seems interesting, but cannot because server-side rendering throws "ReferenceError: window is not defined".

Only importing the Breakpoint causes the error.

Any change to use window only at the point a Breakpoint is actually being used?

Cheers!

**Comment by flexdinesh** [comment]
@timoisalive Thanks for bringing this up. We haven't tested this package out with SSR yet. We'll use this issue to track SSR behaviour.

**Comment by flexdinesh** [comment]
69fe6c7194bd0bb2cbad6f0bac6ba61a7cf6aa4e fixes this error in SSR
