### ISSUE TITLE
We could use `matchMedia` to pass in custom media queries

### ISSUE THREAD

**Issue by flexdinesh** [flexdinesh/react-socks#8]
We could make use  of `matchMedia` to pass in custom media queries

A syntax like this would be really convenient

```jsx
<Breakpoint customQuery={'(min-width: 400px)'}>
  <div>I will render only in mobile devices</div>
</Breakpoint>
```

- Should not interfere with modifiers like`small`, `medium`, etc.
- Should only effect when there are no modifiers.

**Comment by Entkenntnis** [comment]
Using #17 you can write your own logic.

**Comment by flexdinesh** [comment]
@dbryantm Since you mentioned in the other issue that you're interested in new things in this lib, we've been meaning to add this feature for a while. Would be super interesting if this lib could accept breakpoints on the fly and render based on it.

**Comment by dbryantm** [comment]
@flexdinesh sure, I can try and take a look at this. So if I have this correct, you want it only to take effect when there's no breakpoint modifiers like `<Breakpoint sm down/>` otherwise they will supersede the `customQuery`?

**Comment by flexdinesh** [comment]
@dbryantm That's right. Ideally when a `customQuery` is passed we shouldn't expect the parse the breakpoints. Even if breakpoints are passed, we can ignore them.

**Comment by flexdinesh** [comment]
#29 closes this issue
